### ISSUE TITLE
[PORT] Add IAuthenticator to allow for plugging in of Managed Service Identity

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#774] opened 2020-02-24 02:04 UTC
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3255

Azure App Service (and several other resource types) has a Managed Service Identity feature which simplifies management of application identity - see Microsoft.Azure.Services.AppAuthentication for more information.

By having AdalAuthenticator derive from an interface, I can then inject my own MsiAuthenticator that uses AzureServiceTokenProvider to get the token to call the channels.

I can inject my MsiAuthenticator via overriding BuildCredentialsAsync on BotFrameworkHttpAdapter and returning a MsiAppCredentials class that, in turn, returns the MsiAuthenticator 

# Changed projects
* Microsoft.Bot.Connector

**Comment by carlosscastro** [comment] 2020-02-24 02:15
duplicate of https://github.com/microsoft/botbuilder-python/issues/772

**Closed** 2020-02-24 02:16 UTC
