### ISSUE TITLE
Suggested Actions in a waterfall dialog, rolls to next step before user clicks on suggested actions

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botbuilder-python#215] opened 2019-06-19 05:05 UTC
## Version
What package version of the SDK are you using.
v4.4.0.b2

## Describe the bug
Since ChoicePrompts are not yet implemented, a fall back is to use Suggested actions. I've used a suggested action message factory as part of my waterfall step. The intention is to get the use to click on a suggested action and then waterfall to next step where I capture the response via the `im_back` through `activity.text`. The weird behavior I'm observing is that as soon as the suggest action is prompted, it doesn't wait for the user to click on any of the actions before waterfalling. 

## To Reproduce
Example code below
1. Create two waterfall steps in your component dialog
```
async def first_step(self, step: WaterfallStepContext):
          message = MessageFactory.suggested_actions([CardAction(title='a', type=ActionTypes.im_back, value='a'), CardAction(title='b', type=ActionTypes.im_back, value='b'),  CardAction(title='c', type=ActionTypes.im_back, value='c')], 'Choose a color')
         await context.send_activity(message)
         return await step.next(None)

  async def next_step( self, step: WaterfallStepContext):
        # Retrieve the selected trip from the activity im_back and save to state
        print('Inside end')
        matched_trip = re.search('/^(.+?) at (. *)$/ gmi', step.context.activity.text)
        print('+++++++++ Matched information: ', matched_trip.groups())
        return await step.end_dialog()
```
Errors out with 

```
  print('+++++++++ Matched information: ', matched_trip.groups())
**AttributeError: 'NoneType' object has no attribute 'groups'**
```

## Expected behavior
This approach when using ChoicePrompts works perfectly with the NodeJS version of the SDK. As this is not yet implemented in Python, Suggested Actions is the way to go. Expecting a similar behavior a workaround to handle this issue.  
An excerpt from the documentation of Waterfall Dialogs [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0#waterfall-dialogs)

**At each step, the bot prompts the user for input (or can begin a child dialog, but that it is often a prompt), waits for a response, and then passes the result to the next step. The result of the first function is passed as an argument into the next function, and so on.**

## Additional context

[bug]

**Comment by stevengum** [comment] 2019-06-19 23:29
@awaemmanuel this behavior is because of this line:

```py
return await step.next(None)
```

Can you try and return `Dialog.end_of_turn` instead? This should not tell the WaterfallDialog to not start the next step (which is what `return await step.next(None)` does).

**Comment by awaemmanuel** [comment] 2019-06-21 17:22
@stevengum I updated the code like this

`return await step.next(None)` to `return await step.next(MyDialog.end_of_turn)` and it just crashes the code with the following mrest error 

```
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'  
```

Detailed stack trace below.

```
Traceback (most recent call last):
  File "C:\Users\sources\python-bot\lost_and_found\bots\pax_bot.py", line 68, in on_turn
    await self.on_message_activity(context)
  File "C:\Users\sources\python-bot\lost_and_found\bots\pax_bot.py", line 79, in on_message_activity
    await dc.continue_dialog()
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\dialog_context.py", line 144, in continue_dialog
    return await dialog.continue_dialog(self)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\component_dialog.py", line 78, in continue_dialog
    turn_result = await self.on_continue_dialog(inner_dc)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\component_dialog.py", line 138, in on_continue_dialog
    return await inner_dc.continue_dialog()
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\dialog_context.py", line 144, in continue_dialog
    return await dialog.continue_dialog(self)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\component_dialog.py", line 78, in continue_dialog
    turn_result = await self.on_continue_dialog(inner_dc)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\component_dialog.py", line 138, in on_continue_dialog
    return await inner_dc.continue_dialog()
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\dialog_context.py", line 144, in continue_dialog
    return await dialog.continue_dialog(self)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\prompts\prompt.py", line 89, in continue_dialog
    return await dc.end_dialog(recognized.value)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\dialog_context.py", line 171, in end_dialog
    return await dialog.resume_dialog(self, DialogReason.EndCalled, result)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\waterfall_dialog.py", line 88, in resume_dialog
    return await self.run_step(dc, state[self.StepIndex] + 1, reason, result)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\waterfall_dialog.py", line 136, in run_step
    return await self.on_step(step_context)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\waterfall_dialog.py", line 122, in on_step
    return await self._steps[step_context.index](step_context)
  File "C:\Users\sources\python-bot\lost_and_found\dialogs\pax\find_trip_capture_item_dialog.py", line 116, in capture_latest_trip
    return await step.next(None)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\waterfall_step_context.py", line 47, in next
    return await self._wf_parent.resume_dialog(self, DialogReason.NextCalled, result)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\waterfall_dialog.py", line 88, in resume_dialog
    return await self.run_step(dc, state[self.StepIndex] + 1, reason, result)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\waterfall_dialog.py", line 136, in run_step
    return await self.on_step(step_context)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\dialogs\waterfall_dialog.py", line 122, in on_step
    return await self._steps[step_context.index](step_context)
  File "C:\Users\sources\python-bot\lost_and_found\dialogs\pax\find_trip_capture_item_dialog.py", line 147, in prompt_other_trips_if_needed
    await step.context.send_activity(message)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\core\turn_context.py", line 150, in send_activity
    result = await self._emit(self._on_send_activities, output, callback(self, output))
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\core\turn_context.py", line 217, in _emit
    return await logic
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\core\turn_context.py", line 146, in callback
    responses = await context.adapter.send_activities(context, output)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 201, in send_activities
    raise e
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 199, in send_activities
    client.conversations.send_to_conversation(activity.conversation.id, activity)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\botframework\connector\operations\_conversations_operations.py", line 227, in send_to_conversation
    body_content = self._serialize.body(activity, 'Activity')
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 574, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 571, in body
    data = deserializer._deserialize(data_type, data)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1258, in _deserialize
    self._deserialize(local_type, value)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1258, in _deserialize
    self._deserialize(local_type, value)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1267, in _deserialize
    return self.deserialize_data(data, response)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1478, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1478, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1460, in deserialize_data
    return self._deserialize(obj_type, data)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1298, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\Users\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Users\emawa\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "C:\Users\emawa\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "C:\Users\emawa\.virtualenvs\lost_and_found-KRYpeJaq\lib\site-packages\msrest\serialization.py", line 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

**Comment by stevengum** [comment] 2019-06-21 21:43
@awaemmanuel I meant to convey the following: `return Dialog.end_of_turn` at the end of the WaterfallStep. 

Sorry my instructions weren't clear... Let me know if that works.

**Comment by awaemmanuel** [comment] 2019-06-25 18:35
@stevengum I tried this and still get the same crash. Can we connect at some point, if you have the time, and I can screen share?

**Comment by axelsrz** [comment] 2019-10-08 22:44
Hello @awaemmanuel , I couldn't reproduce in 4.5.0b4 with this code:

```python
async def first_step(self, step: WaterfallStepContext):
        message = MessageFactory.suggested_actions([CardAction(title='a', type=ActionTypes.im_back, value='a'), CardAction(title='b', type=ActionTypes.im_back, value='b'),  CardAction(title='c', type=ActionTypes.im_back, value='c')], 'Choose a color')
        await step.context.send_activity(message)
        return ComponentDialog.end_of_turn

    async def next_step(self, step: WaterfallStepContext):
        # Retrieve the selected trip from the activity im_back and save to state
        print('Inside end')
        # matched_trip = re.search('/^(.+?) at (. *)$/ gmi', step.context.activity.text)
        # print('+++++++++ Matched information: ', step.context.activity.text)
        await step.context.send_activity(f"You picked: {step.context.activity.text}")
        return await step.end_dialog()
```

I get this:
![Screen Shot 2019-10-08 at 3 33 39 PM](https://user-images.githubusercontent.com/5943395/66438502-b4199680-e9e1-11e9-804f-2a94493c48cf.png)

Then, after clicking 'b':
![Screen Shot 2019-10-08 at 3 33 57 PM](https://user-images.githubusercontent.com/5943395/66438578-f80c9b80-e9e1-11e9-9f57-89c260fbfeb7.png)


The error you're mentioning: `**AttributeError: 'NoneType' object has no attribute 'groups'**` It's because of the regex you're defining (which doesn't find any match) and it's returning None; but I believe the behavior of Suggested Actions here is the expected.

I'm closing the issue

**Closed by axelsrz** 2019-10-08 22:44 UTC
Labels: 4.6, approved, bug
