### ISSUE TITLE
Bug in set_value of StateManager

### ISSUE THREAD

**Issue by RobinVds** [microsoft/botbuilder-python#1908] opened 2022-01-29 20:55 UTC
## Version
Latest

## Describe the bug
When I try to set the state value via the state manager I get the following error:

```
  File "/home/robin/dev/ask-waldo/ask-waldo-teams-chatbot/.venv/lib/python3.8/site-packages/botbuilder/dialogs/memory/dialog_state_manager.py", line 293, in try_get_value
    i_first = path.upper().rindex(first)
ValueError: substring not found
```

## To Reproduce
Call set_value on state_manager: 
` step_context.state.set_value("user.path", "a value")`

## Expected behavior
I do not receive an error and the state is updated.

## Additional context
This can be fixed as follows:
In file: `botbuilder-python/libraries/botbuilder-dialogs/botbuilder/dialogs/memory/dialog_state_manager.py`

Update:
           ` i_first = path.upper().rindex(first)`

To:
```
        try:
            i_first = path.upper().rindex(first)
        except ValueError:
            i_first = -1
```

Or just fix that hacky thing that is being done there :)

**Comment by ramfattah** [comment] 2022-02-01 18:41
Hi @RobinVds, I'm looking into this issue.

**Comment by ramfattah** [comment] 2022-02-04 05:31
Hello @RobinVds, I was able to reproduce this same issue. Just created a PR regarding this. Thank you for finding this bug.

**Comment by ramfattah** [comment] 2022-02-21 19:52
Closing due to fixed PR.

**Closed by ramfattah** 2022-02-21 19:52 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to, needs-triage
