### ISSUE TITLE
Internal bot on SDK v4 does not work with New Teams

### ISSUE THREAD

**Issue by gykung** [microsoft/botbuilder-python#2035] opened 2023-11-07 16:42 UTC
## Version
I am using SDK v4. This is an internal bot served on MS teams via ngrok.

## Describe the bug
The bot works on Teams Classic. However, it shows the following error in New Teams.

## To Reproduce
Simply launch the bot on New Teams.

## Expected behavior
The bot works on Teams Classic. However, it shows the following error in New Teams.

## Screenshots
![image](https://github.com/microsoft/botbuilder-python/assets/70024742/c4c34e9d-2d46-474c-8d7c-dac34610196f)

## Additional context
Nil.

**Comment by aacebo** [comment] 2023-12-12 18:26
I am not able to reproduce this issue using version `4.14.7`, can you link me to your code?

**Comment by pablomarin** [comment] 2023-12-14 17:40
I confirm this is an issue with multiple customers. 
The Teams Channel in the bot Service doesn't work with the New Teams. It works good with the classic teams. This is not an issue with the bot builder SDK, but with the Bot Service in the portal.

![Screenshot 2023-12-14 at 11 18 58 AM](https://github.com/microsoft/botbuilder-python/assets/2685728/8c3ab287-874f-43a2-b890-9deb73ef5a0e)

**Comment by aacebo** [comment] 2024-01-22 22:33
closing as this is has been confirmed to not be an issue with the SDK

**Closed by aacebo** 2024-01-22 22:33 UTC
Labels: bug
