### ISSUE TITLE
on_members_added_activity doesn't work in a derived class of TeamsActivityHandler

### ISSUE THREAD

**Issue by yosshy** [microsoft/botbuilder-python#1662] opened 2021-04-28 15:39 UTC
## Version
4.13

## Describe the bug
I created a Teams bot using on_members_added_activity() to send a hello message to chat users, but it doesn't work. It uses a derived class of TeamsActivityHandler.

## To Reproduce
1. Deploy a bot using on_members_added_activity() method and a derived class of TeamsActibityHandler.
2. Log-in MS365 as an administrator.
3. Open Admin page and create a new Teams account.
4. Open Teams and install a manifest for the bot.
5. Log-out from MS365.
6. Log-in Teams as the new Teams account created at step 3.
7. Click the chat icon.
8. Create a chat with the bot and send a message.
9. Confirm no message from the bot.

## Expected behavior
See a hello message from the bot at step 9.

## Screenshots
No

## Additional context
No

## Additional information
TeamsActivityHandler calls several handler methods with super(). IMO, it should call them using self.

* https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L184
* https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L588
* https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L780
* https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L836

**Comment by axelsrz** [comment] 2021-04-30 22:39
Hello @yosshy thanks for submitting this. We will investigate this issue and in the case of turning out a bug we'll provide a fix in our next cycle.

**Comment by axelsrz** [comment] 2021-05-05 04:44
Hello @yosshy, I believe what you mention in the description as a bug is the expected behavior.

From the documentation page of the [activity handler](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp#teams-specific-activity-handlers): "(refering to OnTeamsMembersAdded) _... The method can be overridden to handle members joining a team._". After confirming this description with other team memebers, this means that the `on_members_added_activity` method should only trigger when a new member is added to a **team** in which the bot is participant (including the bot), not in private conversations of users with the bot.

As for your question regarding the calling of other ActivityHandler methods with super() instead of self, the purpose is to call the method on the parent class acording to the MRO (in this case ActivityHandler) hence the use of super(); if we used self we would introduce a recursive infite loop in this [method ](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L184) and this [method](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L588), as for the other 2 methods ([L780 ](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L780)and [L836](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L836)), that could result in confusing behavior if these methods where implemented in a child class without considering side effects in teams specific methods.

Please let us know if you have any further questions/comments, if not, we'll proceed to close this issue.

**Comment by yosshy** [comment] 2021-05-07 14:38
Hi @axelsrz,

Thank you for your description. I'm sorry, pointing at 2 methods (L184 and L588) is perfectly my misunderstanding. But using super() for other 2 methods (L780 and L836) still seems a kind of bug for me because:

1. Both TeamsActivityHandler.on_teams_members_added() and TeamsActivityHandler.on_teams_members_removed() have logic to append extra information for on_members_added_activity() / on_members_removed_activity(). They don't look just stubs to override but, of course, we can override them.
2. Both [ActivityHandler.on_members_added_activity()](https://github.com/microsoft/botbuilder-python/blob/4003d713beb8fb986a01cfd11632eabc65858618/libraries/botbuilder-core/botbuilder/core/activity_handler.py#L148) and [ActivityHandler.on_members_removed_activity()](https://github.com/microsoft/botbuilder-python/blob/4003d713beb8fb986a01cfd11632eabc65858618/libraries/botbuilder-core/botbuilder/core/activity_handler.py#L170) are just stubs and do nothing. Calling them is nonsense. 

My description about how to reproduce may look wrong, but using super() at L780 is a real problem for me. I have to override on_teams_member_added() to avoid the bug now.

**Comment by axelsrz** [comment] 2021-05-13 18:07
@yosshy I'm opening #1674 to better track and solve the issue you suggested. As for this issue, I'm closing it due to the members_added_activity behaving as expected in the scenario described.

**Closed by axelsrz** 2021-05-13 18:07 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported, needs-triage
