### ISSUE TITLE
KeyError: 'access_token' while sending Activity via Turn Context

### ISSUE THREAD

**Issue by NORXND** [microsoft/botbuilder-python#1434] opened 2020-11-23 11:26 UTC
## Version
botbuilder-schema - 4.11.0
botbuilder-core - 4.11.0
Python 3.8.6

## Describe the bug
Error occurs when trying to send activity via turn context.
[Traceback](https://pastebin.com/embed_iframe/vxZCKpYS)

## To Reproduce
Steps to reproduce the behavior: Try to send Activity
[Code example](https://pastebin.com/embed_iframe/fpBaWitD)

## Expected behavior
Send message to channel.

## Additional context
I did not change the part of the code responsible for this error.

**Comment by jwiley84** [comment] 2020-11-23 19:05
Can you share your environment? is this a deployed bot on azure or is it local? What channel is this occurring on? Can you share more of your bot's code? What you shared is not enough to repro your issue.

**Comment by NORXND** [comment] 2020-11-24 07:41
@jwiley84 I'm planning to host it on Heroku, but I cannot share code via it. Anyway, the same error is present on Repl it.
Bot operates on these files:

- server.py

- teams_platform/main.py

- teams_platform/commands/help.py

- teams_platform/commands/wiki.py

https://repl.it/@NORXND/Edu

Thanks for help!

**Comment by NORXND** [comment] 2020-11-26 06:58
@jwiley84 You still cant reproduce my issue?

**Comment by jwiley84** [comment] 2020-12-01 17:09
your use of the bot framework component is beyond the scope of what I'm used to seeing, and I'm trying to parse what quite what's going on with it. Thank you for  your patience.

**Comment by NORXND** [comment] 2020-12-02 07:35
Ok, I'm waiting patiently.

**Comment by hcyang** [comment] 2020-12-05 18:40
hi @jwiley84, any update?

**Comment by v-kydela** [comment] 2020-12-10 23:45
@NORXND - While the repl.it code does not run successfully for me, I did notice this error message during the installation:

```
ERROR: botframework-connector 4.11.0 has requirement requests==2.23.0, but you'll have requests 2.25.0 which is incompatible.
```

Have you tried downgrading to requests 2.23.0?

**Comment by NORXND** [comment] 2020-12-14 07:11
Hello @v-kydela , sorry for late reply. I have tried downgrading it to 2.23 but it didn't help. Still the same error.

**Comment by v-kydela** [comment] 2020-12-15 01:13
@NORXND - From the traceback you shared, it looks like MSAL is returning a dictionary that doesn't include the access token, so it's strange that it wouldn't just throw an error sooner. I have a few questions.

1. Can you verify that your app ID and password are successfully loaded into the adapter?
1. Can you reproduce the problem when you run the bot locally?
1. Do you have this problem when you run the Python [samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot)?
1. What did you mean when you said "I did not change the part of the code responsible for this error"?

**Comment by NORXND** [comment] 2020-12-15 15:12
I will try it. About 4. For example, I have a function that is reading data from Wikipedia, and another function is for sending it to Teams. So I mean that I did not change this function that is responsible for sending. And it throws an error at sending.

**Comment by v-kydela** [comment] 2020-12-15 19:22
@NORXND - You did not change the function from what? Did you start with some template or sample? Can you link to it?

**Comment by NORXND** [comment] 2020-12-16 08:39
> 
> 
> @NORXND - You did not change the function from what? Did you start with some template or sample? Can you link to it?

No. I started from scratch. You can see my code if you want: https://github.com/NORXND/Edu/tree/dev-beta/
The bot for Teams is under "teams_platform" folder.

**Comment by v-kydela** [comment] 2020-12-17 18:05
@NORXND - Thank you linking to your GitHub repo. So you just meant your example code is the same as your actual code?

**Comment by v-kydela** [comment] 2020-12-18 01:02
@NORXND - Your code is unlike any bot I've seen. You've provided both a repl.it page and a GitHub repo, but I don't know how to run your code in either.

In Repl.it I try forking and then clicking Run and it fails like this:

![image](https://user-images.githubusercontent.com/41968495/102561466-ace02500-4089-11eb-8352-bb41b4ec522a.png)

Is there something I'm supposed to do instead of clicking Run?

If you can provide instructions for how to run your code in either Repl.it or from your GitHub repo, that would help us reproduce the problem.

**Comment by NORXND** [comment] 2020-12-18 07:00
Hello. To run ONLY Teams Bot, you will need to run the server.py file. (You can copy my repo). But t you need to have an App ID and Password for BotFrameworkAdapterSettings. They are provided by two environment variables "TEAMS_APPID" and "TEAMS_TEAMS_PASSWORD" or simply put into line 12 of teams_platform\main.py. If you want to test it in the emulator, or local server. You must change the host in line 47 in server.py.
Thanks for helping!

**Comment by v-kydela** [comment] 2020-12-18 17:29
@NORXND - I'm sorry but you'll really need to provide step-by-step instructions because we don't know your project like you do. For example, is there a specific version of Python we should use to run server.py?

Also, can you answer my previous questions? You said you would "try it":

> 1. Can you verify that your app ID and password are successfully loaded into the adapter?
> 1. Can you reproduce the problem when you run the bot locally?
> 1. Do you have this problem when you run the Python [samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot)?

**Comment by NORXND** [comment] 2020-12-19 09:15
@v-kydela Hello, 
1. App ID and password are loaded into an adapter. I have verified that.

2. No, I can't, because there is some problem with the emulator, and my app didn't get any response:
![obraz](https://user-images.githubusercontent.com/26685237/102685380-7668ee00-41e0-11eb-9450-41789c5fbc56.png)
![obraz](https://user-images.githubusercontent.com/26685237/102685391-87b1fa80-41e0-11eb-9a4e-f63630a86a56.png)
I must add that emulator worked before.
3. I tried on repl.it: `Traceback (most recent call last):
  File "app.py", line 88, in <module>
    raise error
  File "app.py", line 86, in <module>
    web.run_app(APP, host="localhost", port=CONFIG.PORT)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web.py", line 419, in run_app
    loop.run_until_complete(_run_app(app,
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web.py", line 359, in _run_app
    await site.start()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/web_runner.py", line 100, in start
    self._server = await loop.create_server(  # type: ignore
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 3978, 0, 0): cannot assign requested address`
And on local, problem with emulator
![obraz](https://user-images.githubusercontent.com/26685237/102685743-10ca3100-41e3-11eb-9a74-11e8db8f8d72.png)

If you want, I can prepare a version of my code only with the Teams bot.

**Comment by v-kydela** [comment] 2020-12-22 01:39
@NORXND - The simpler you can make the repro the better, but we still don't have any kind of repro. It was good to provide your code, but my understanding of Python is that it's not necessarily obvious how to run Python code. Are you willing to provide instructions like I asked for? You can see an example of step-by-step instructions in the [samples](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/02.echo-bot/README.md):

> - Clone the repository
> ```bash
> git clone https://github.com/Microsoft/botbuilder-samples.git
> ```
> - In a terminal, navigate to `botbuilder-samples\samples\python\02.echo-bot` folder
> - Activate your desired virtual environment
> - In the terminal, type `pip install -r requirements.txt`
> - Run your bot with `python app.py`

There's more to the repro than just the code. There are a lot of things about your environment we don't know. We don't know what version of Python or pip you're using. We don't know if you're using a virtual environment. My understanding is that repl.it should solve the problem by allowing us to run the same code in the same environment, but as I've said I cannot successfully run the code in repl.it so I cannot try to reproduce the issue. I will ask again, is there something I'm supposed to do instead of clicking Run?

**Comment by NORXND** [comment] 2020-12-22 07:35
Hare, you have simplified code. Only what you need to do is insert App ID and Password in line 10 in file teams_platform/main.py (Into adapter settings) and then run server.py. If you need you can change the host or port in Flask. I have added a sample command to use. You use it like @YOURBOTNAME pomoc
I hope it will work for you and you will be able to reproduce this error.
[Edu-TeamsOnly.zip](https://github.com/microsoft/botbuilder-python/files/5728380/Edu-TeamsOnly.zip)

**Comment by v-kydela** [comment] 2020-12-23 00:17
@NORXND - I am able to run your bot now based on your newest zip file, but I am not able to reproduce the key error. The bot runs fine.

![Teams](https://user-images.githubusercontent.com/41968495/102944778-a2020780-4470-11eb-878f-4269a1fec48d.png)

You'll need to help me make our environments as similar as possible to see if we can identify the difference that's making it work on my machine and not yours.

1. Are you using a virtual environment?
1. Unfortunately your minimal example is a little too minimal in that it doesn't include requirements.txt, but it looks like your example depends on asyncio, flask, botbuilder.core, and botbuilder.schema. Can you verify that you've installed the latest versions of each of these packages?
1. I had to modify server.py by changing `/teams/event` to `/api/messages`, `127.168.1.1` to `127.0.0.1`, and `5000` to `3978`. Are you able to successfully run the bot locally after making those modifications?
1. Are you reproducing the error on Teams or some other channel?
2. What types of conversations can you reproduce the error in?
2. Have you tried testing your bot on Teams locally using a tunneling service?
3. Have you tried any other channels?

**Comment by NORXND** [comment] 2020-12-29 09:04
1. First I noticed an error on Heroku using "config vars"
2. Hare is my full requirements.txt
`mysql-connector==2.2.9
boto==2.49.0
discord.py==1.5.1
Flask==1.1.2
requests==2.23.0
botbuilder-schema==4.11.0
botbuilder-core==4.11.0`
You won't need `discord.py` and `mysql-connector` for latest zip.
3. I will need to test it
4. Only teams
5. In Team chat
6. Sorry but I have never used it before, and I don't know what is it
7. No

**Comment by v-kydela** [comment] 2020-12-29 18:01
@NORXND 

When debugging your bot, it's important to be able to run your bot locally so you can run it in debug mode while still chatting on your target channel. Most people use ngrok, and you can read more about that here: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok

I use TunnelRelay: https://techcommunity.microsoft.com/t5/microsoft-teams-blog/introducing-tunnel-relay/ba-p/149990

It looks like TunnelRelay may only work on Windows. What's your OS?

**Comment by NORXND** [comment] 2020-12-30 19:08
> It looks like TunnelRelay may only work on Windows. What's your OS?
Microsoft Windows 10 2004 (19041.685)

**Comment by v-kydela** [comment] 2020-12-30 23:12
@NORXND - All right, well then it sounds like you can use Tunnel Relay. You may want to start out with ngrok at first anyway because it's simpler. Get used to tunneling because it will be vital to testing and debugging your Teams apps. The idea behind tunneling is that you get a remote endpoint that you can provide as your bot's endpoint (e.g. in your bot resource in the Azure portal) that forwards requests to your local endpoint. You can't use a local endpoint (like localhost:3978) for things like Teams, so having a remote endpoint that just forwards everything to the local endpoint is a way around that problem.

**Comment by v-kydela** [comment] 2021-01-08 22:43
@NORXND - Are you still working on this?

Can you post a screenshot of where you're getting your app ID and password from? Is it possible that you've made the same mistake as [this other developer](https://github.com/microsoft/BotBuilder-Samples/issues/2998#issuecomment-755027382) by using the ID from the client secret rather than the actual AAD app ID?

**Comment by NORXND** [comment] 2021-01-09 08:44
Hello @v-kydela. No, I gave up. The bot idea was bad since clients move to MS Teams where they had all futures they need + This error.

App ID: https://imgur.com/a/rPpJdFL
I generated a password from App Studio, but I cannot find password/button to generate one. Strange

**Comment by v-kydela** [comment] 2021-01-11 17:58
@NORXND - I can't really tell where that app ID is, but it looks like it might be in the bots tab of the manifest editor in App Studio. That would be one correct place to get it from, but since you're using App Studio you need to be careful not to use the Teams app ID instead of the bot's AAD app ID.

If there's no button to generate a new password, it may be because you already have two passwords. You will need to delete one before generating a new one. It may be better to follow the link to the app registration portal so you'll have more control. Perhaps it's possible that the password that you're using expired. It may be a good idea to generate a new password in any case for testing purposes, or even to create an entirely new app registration. It's hard to say because I don't know what's wrong with your current app ID and password.

When you say you gave up, does that mean you'd like to close this issue?

**Comment by v-kydela** [comment] 2021-01-12 20:44
@NORXND - Is it possible that you have the same problem as [this developer](https://stackoverflow.com/questions/65523957/is-it-possible-to-run-a-teams-bot-without-password-or-do-i-have-a-problem-when-c/65570967#comment116117296_65570967)? Their AAD app registration didn't support accounts in all organizations

**Comment by v-kydela** [comment] 2021-01-19 22:47
@NORXND - Do you still need help?

**Comment by NORXND** [comment] 2021-01-20 06:48
No, maybe if I will have some time I will test it out but for now, I think this is some environment-side bug or some type. (for example, I put something in the wrong place) You can focus on other issues @v-kydela.

**Closed** 2021-01-20 19:24 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by kotofos** [comment] 2022-08-14 11:01
Get the same error when the AppPassword was wrong.
botbuilder-core==4.13.0

**Comment by yellalena** [comment] 2024-03-15 06:00
Hi all!
In case someone else lands in this issue, I had this error when trying to run an older example utilizing **BotFrameworkAdapter**, which is now deprecated and in BotBuilder-Samples repo it's changed to use **CloudAdapter**. I didn't understand what the problem was as I was using Emulator and didn't provide any APP_ID or APP_PASSWORD to be wrong. After I switched to use CloudAdapter, the very same code worked perfectly!

**Comment by Bennoo** [comment] 2024-03-21 17:26
Hey there!
I am having the same issue, using CloudAdapter.
When I am trying the bot through TEAMS with a azure bot deployed with an ID and a password (secret) I have the issue, when I try my bot from the emulator without any ID or password it is working.
And when I try the bot with the ID and PAssword with the emulator, it says that the password is incorrect (I use the secret generated in the azure portal)

I am lost, I would like to test my bot through teams on step further than the emulator..

**Comment by Bennoo** [comment] 2024-03-22 10:25
I finally found what was my issue.. I let it here for someone looking for the same. It was due to the fact that I am working with the python version of the framework and there is no support for single-tenant azure bot applications. I had to delete and recreate a new bot in azure with multi-tenant, now it is working..
