### ISSUE TITLE
Cannot install -r .\requirements.txt and botframework-connector==4.14.2 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by Incedendo** [microsoft/botbuilder-python#1956] opened 2022-07-25 15:48 UTC
### Use this [query](https://github.com/Microsoft/botbuilder-python/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
I'm working on building a chatbot for Azure Client Storage team using AzureBotFramework Python SDKs. I'm always frustrated when trying to install the required dependencies specified in requirement.txt with the command "pip install -r requirement.txt". For my use case, I need azure-kusto-data==2.1.3 which support asynchronous io operations (azure-kusto-data[aio]). The issue is: azure-kusto-data 2.1.3 depends on msal~=1.9.0, while botframework-connector 4.14.2 depends on msal==1.6.0

**Describe the solution you'd like**
A clear and concise description of what you want to happen:
A new release of botframework python SDK that update msal's required version to 1.9.0 to be compatible with azure-kusto-data >=2.1.3

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/17934623/180820468-cac6eccc-dabc-4328-aa42-18eb08c1ba56.png)

**Comment by ramfattah** [comment] 2022-07-25 17:30
Hi @Incedendo,

I was able to reproduce this issue when using `azure-kusto-data==2.1.3` package. 

Attached is a minimal repro zip bot project. Failed after running the command `pip install -r requirements.txt`:
[02.echo-bot.zip](https://github.com/microsoft/botbuilder-python/files/9183515/02.echo-bot.zip)

**Comment by Incedendo** [comment] 2022-07-25 18:36
Any suggestions on potential solutions?

**Comment by tracyboehrer** [comment] 2022-07-28 15:31
Closing.  Axel is working with engineer.

**Comment by gmichels** [comment] 2022-08-16 17:56
I have a similar issue due to the requirement on `msal==1.6.0` and was wondering if there was ever a solution to this.

**Comment by tracyboehrer** [comment] 2022-09-15 15:19
Scheduling for next patch

**Comment by kristapratico** [comment] 2022-10-03 17:27
I'm getting similar reports from customers when trying to use botbuilder with the Azure SDKs. Applications can pin dependencies, but libraries should not pin exact dependencies. A library should use a [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release) identifier for the dependency.

**Closed** 2022-10-26 13:07 UTC
Labels: ExemptFromDailyDRIReport, needs-triage, feature-request
