### ISSUE TITLE
Add user-assigned managed identity for Python SDK 🙏🏻

### ISSUE THREAD

**Issue by denissa4** [microsoft/botbuilder-python#1928] opened 2022-03-02 18:07 UTC
**Is your feature request related to a problem? Please describe.**
Azure Bot released new types of bots, user-assigned managed identity is awesome, but we can't use it because Botbuider-python doesn't have support for it

**Describe the solution you'd like**
Please add user-assigned managed identity for Python SDK 🙏🏻

**Describe alternatives you've considered**
We don't have any alternatives

**Comment by RonMallory** [comment] 2022-08-03 18:34
related #1790

**Comment by tracyboehrer** [comment] 2022-10-27 18:51
Duplicate of #1790

**Closed by tracyboehrer** 2022-10-27 18:51 UTC
Labels: needs-triage, feature-request
