### ISSUE TITLE
Suggested Action with CardAction not working as expected.

### ISSUE THREAD

**Issue by GreatHavoc** [microsoft/botbuilder-python#2118] opened 2024-05-30 04:47 UTC
## Version
Bot Framework Python SDK.
botbuilder-core==4.14.8
botbuilder-dialogs==4.14.8
botbuilder-schema==4.14.8
botframework-connector==4.14.8
botframework-streaming==4.14.8
## Describe the bug
IDEA: I want to show the option to the user on the bot webchat where he will click to open a link and come back to bot again to continue the flow.

Issue: I am using the prompt to show the user suggested actions and added the action to the choices of the prompt but the issue is after clicking on the suggested action the link opens but i didn't get any response that the button is clicked because of that i can't continue the flow without knowing what isd clicked or selected by the user.

Reference Code:
return await step_context.prompt(ChoicePrompt.__name__,PromptOptions(
            style=ListStyle.suggested_action,
            choices=[Choice("Link1"),Choice("Link2"),Choice('Link3',action=CardAction(title="Track Credit Card Application",type="openUrl",value="https://xyz.com")),Choice("Apply Now For Credit Card",action=CardAction(title="xyz link",type="openUrl",value="www.xyz.com",display_text="xyz",text="xyz"))]))

## To Reproduce
1. Go to 'Open Emulator'
2. Click on 'Suggested Action with Link'

## Expected behavior
After the user clicks the suggested action the display_text will be shown on the chat user response.

## Screenshots
Example Suggested Options with OpenLink as CardAction.
![image](https://github.com/microsoft/botframework-sdk/assets/77237918/66973558-df62-45e7-ac67-5dd0055dedcf)
After clicking any one of the above:
![image](https://github.com/microsoft/botframework-sdk/assets/77237918/5ebff3b0-d9ed-4bdd-8ed6-69a9396c2a17)
Nothing is displayed after clicking the button, like it will show selected option in the user side of the chat window.

**Comment by dmvtech** [comment] 2024-07-15 20:28
Can reproduce. Closing as duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/5200. Not specifically related to Python SDK.

**Closed by dmvtech** 2024-07-15 20:28 UTC
Labels: customer-reported, Bot Services, customer-replied-to
