### ISSUE TITLE
ConfirmPrompt errors out with "NameError: name 'ChoiceRecognizer' is not defined"

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botbuilder-python#214] opened 2019-06-19 02:13 UTC
## Version
What package version of the SDK are you using.
v4.4.0.b2

## Describe the bug
When using a `ConfirmPrompt` Dialog, if the user clicks `Yes` or `No`, bot errors with ChoiceRecognizer is not defined. I see that in the flight booking samples, ConfirmPrompt is commented out. Possibly an incomplete implementation

## To Reproduce
1. Add a `ConfirmPrompt` to your dialogs
1. Use `step.prompt(ConfirmPrompt.__name__)` to reference it. 
1. Start chat bot
1. Trigger prompt
1. Click `Yes` or `No`

## Expected behavior
The Python SDK `ConfirmPrompt` Dialog should work when I click on `Yes` or `No` prompts. It should work exactly how the `C#` and `TypeScript` SDKs work

## Additional context
  File "C:\Users\.virtualenvs\laf-KRYpeJaq\lib\site-packages\botbuilder\dialogs\prompts\confirm_prompt.py", line 67, in on_recognize
    results = ChoiceRecognizer.recognize_boolean(message.text, culture)
NameError: name 'ChoiceRecognizer' is not defined

[bug]

**Comment by axelsrz** [comment] 2019-06-20 23:32
Duplicate of #185

**Closed by axelsrz** 2019-06-20 23:32 UTC
