### ISSUE TITLE
NumberPrompt Dialog errors out with NameError: name 'ChoiceRecognizer' is not defined

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botbuilder-python#218] opened 2019-06-19 14:04 UTC
## Version
v4.4.0.b2

## Describe the bug
Related to #216, #217 and #214 
Please read #216 and #217 before this since they are directly related to NumberPrompt. After putting in those simple fixes in my fork of the SDK, it finally errors out with NameError: name 'ChoiceRecognizer' is not defined. Seems like a direct issue with #214  and possibly a copy and paste issue from ConfirmPrompt

## To Reproduce
Bug in code: **botbuilder\dialogs\prompts\number_prompt.py:58**

## Expected behavior
NumberPrompt should work without any errors. 

## Additional context

[bug]

**Comment by axelsrz** [comment] 2019-06-20 23:34
Duplicate of #185

**Closed by axelsrz** 2019-06-20 23:34 UTC
